print("안녕하세요")
print("반갑습니다")
print("외대 컴공의 빛은")
print("결국 임창용인가..")
print("경기도 남양주시")
print("나는 음악을 좋아해")
print("창모와 체인스모커스를 얼마나 좋아하는지")
for _ in range(1, 4):
  print("심심해!")
  print("pull-request실습")
